version: '2.2'
services:
  php:
    container_name: "meeduphp"
#    build:
#      context: ./docker
    image: registry.cn-hangzhou.aliyuncs.com/xiaoteng/meedu-php:v1
    volumes:
      - ./:/var/www/html/
    restart: always
    expose:
      - "9000"
    networks:
      - meedu-net

  nginx:
    container_name: "meedunginx"
    image: nginx:1.15.7
    ports:
      - "9006:80"
      - "4430:443"
    volumes:
      - .:/var/www/html/:rw
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./docker/nginx/logs:/var/log/nginx/:rw
      - ./docker/nginx/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - meedu-net

networks:
  meedu-net:
    external: true
